### ISSUE TITLE
Installation conflict with jaraco.itertools

### ISSUE THREAD

**Issue by 0-wiz-0** [jaraco/jaraco.functools#16]
Both jaraco.itertools and this install `${PYSITELIB}/jaraco/__init__.py` - this is a problem for packaging systems which install all packages into the same prefix and want to register a file for one package only. Please solve this conflict.
Filed for both projects, see https://github.com/jaraco/jaraco.itertools/issues/9

**Comment by jaraco** [comment]
Hey Wiz.

This project shares the `jaraco` namespace with dozens of other packages according to the [best practices defined in the packaging user's guide](https://packaging.python.org/guides/packaging-namespace-packages/), just like other namespaces like [backports](https://pypi.org/project/backports/) (including [configparser](https://pypi.org/project/configparser]), [zc](https://pypi.org/project/zc.lockfile), and others. It's had this behavior since its inception.

Eventually, the `jaraco` namespace will switch to using [implicit namespace packages](https://www.python.org/dev/peps/pep-0420/), but until then, it must necessarily define this file in all packages that share the namespace.

> this is a problem for packaging systems... [that] want to register a file for one package only.

I would raise the issue with those packaging systems or possibly with [packaging problems](/pypa/packaging-problems). This project will continue to use whatever the best practices are for grouping packages into a shared namespace.

**Comment by 0-wiz-0** [comment]
A last comment: I still think that one file should only be installed by one program. So if both jaraco.itertools and jaraco.functools want to have an `jaraco/__init__.py`, then some jaraco.something should install that and both should depend on it.
