### ISSUE TITLE
Add Asyncio version of Throttler

### ISSUE THREAD

**Issue by zinsserzh** [jaraco/jaraco.functools#8]
As discussed in https://github.com/jaraco/irc/issues/146
We need to have an asyncio implementation of `Throttler`.

I'm having a hard time understanding `Throttler.__get__`. Can you provide me with a scenario where it's used?

Also, `Throttler` does not use a lock. Are you assuming that it is always called from the same process/thread? Anyway, I do think `AioThrottler` should include a lock to prevent race conditions. However, this will create a deadlock if the function calls itself recursively (btw, there is no `Rlock` in asyncio). What do you think?

How do you like the name `AioThrottler`?

Where should I put the class? Should I do it in another file? How should I construct tests? Asyncio syntax causes syntax errors in python <= 3.4

**Comment by jaraco** [comment]
Apologies for the long delay in responding. This fell off my radar.

> Can you provide me with a scenario where `Throttler.__get__` is used?

A `__get__` method makes that class a [descriptor](https://docs.python.org/3/howto/descriptor.html). If you remove that method, [test_throttled_method](https://github.com/jaraco/jaraco.functools/blob/6b97b285003806e37d92709e98d444810dd90fd2/test_functools.py#L52-L59) will fail.

Basically what it does is whenever you call an object with a throttled method, `__get__` will bind the `self` parameter to the function, and then use `first_invoke` to ensure that `self._wait` is invoked before each call to the decorated function.

> Are you assuming that it is always called from the same process/thread?

Same process, definitely. Same thread, not necessarily. As a general rule, I design functions to be thread-safe and try to mark them as thread unsafe when they're not. So if this function is in fact not threadsafe where you'd expect it to be, it's a bug that it's not marked as such. In a cursory review, I think you may be right that it may be thread unsafe. I'd be interested in adding a test that demonstrates a failure in a multithreaded environment. Regardless, it's a bug if one could illustrate a scenario where it would fail (which I think I could do). I surmise that if it's not threadsafe, the behavior you'll get is under-throttled function calls, but otherwise the code will run as expected.

I would like to make it threadsafe, and adding a lock might be suitable. It may not even be subject to a deadlock as you worry, even in a recursive scenario, because the lock would be around the `wait` which exits before the actual function call. That's probably also worthy of a test.

> Where should I put the class?

Although in the downstream issue I suggested contributing the change here first, it may make sense for expediency to implement the `AioThrottler` first in `irc` and then we can optionally port it back here as appropriate... especially if that eases the testing.

**Comment by jaraco** [comment]
I'm going to close this issue here for now. Feel free to continue to pursue this issue here or in the irc lib, and I'll be happy to re-activate the issue as needed.
